Groupby agrupamdo dados no df:

In [14]:
import pandas as pd
import re
df = pd.read_csv('house.csv')
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63018,Roxburgh Park,3 Carr Pl,3,h,566000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63019,Roxburgh Park,9 Parker Ct,3,h,500000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63020,Roxburgh Park,5 Parkinson Wy,3,h,545000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63021,Thomastown,3/1 Travers St,3,u,NaN,PI,Barry,31/03/2018,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
63022,Williams Landing,1 Diadem Wy,4,h,NaN,SP,Aussie,31/03/2018,3027,Western Metropolitan,1999,17.6,Wyndham City Council

In [17]:
df.groupby(['SellerG']).mean()

TypeError: agg function failed [how->mean,dtype->object]

In [15]:
df.groupby(['SellerG']).sum()

,Suburb,Address,Rooms,Type,Price,Method,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
SellerG,,,,,,,,,,,,
@Realty,CraigieburnCraigieburnBroadmeadowsCraigieburnR...,59 Balyang Wy66 Northern Cr83 Waranga Cr2 Bens...,98,hhhhhhhhhthuhhhtthhhhhhhhhh,15727500.0,SSPISPISPWSVBSSVBPISPPIPISSSPNPIPISSVBVBPN,1/07/20171/07/20173/03/20183/06/20174/03/20176...,83344,Northern MetropolitanNorthern MetropolitanNort...,229794,430.6,Hume City CouncilHume City CouncilHume City Co...
A,DallasDallasGreenvaleGlenroyMeadow HeightsHadf...,8 Corinella Cr5 Leigh Ct27 Langton Wy3/24 Gran...,27,hhhhhhhhh,4359000.0,SPISPVBSPSSPIS,5/05/20187/04/20187/04/20189/06/201811/11/2017...,27431,Northern MetropolitanNorthern MetropolitanNort...,39708,121.8,Hume City CouncilHume City CouncilHume City Co...
AIME,Ashwood,2/11 Salisbury Rd,4,t,980000.0,PI,18/03/2017,3147,Southern Metropolitan,2894,10.2,Monash City Council
ASL,TemplestoweDoncasterRingwoodCroydonReservoirCo...,2/61 Wood St48 Winston Dr62 Ringwood St16 Dona...,34,thhhhhhhhh,11037500.0,SSSSSPSSSSS,1/04/20172/06/20184/06/20166/08/20169/09/20171...,31049,Eastern MetropolitanEastern MetropolitanEaster...,97020,148.2,Manningham City CouncilManningham City Council...
Abercromby's,MalvernToorakToorakMalvern EastAlbert ParkBalw...,2A Robinson St5 Theodore Ct12/417 Toorak Rd256...,219,hhuhhhuhuhuhhhhthhhuhhuhhuhhhhuhuhhhuhhhhhuuhh...,90422000.0,SNSSPVBSSSPPISSSPSNVBVBSNSSPSSSSSSPNSNSASPSNSV...,1/04/20172/06/20182/06/20183/03/20183/06/20173...,213474,Southern MetropolitanSouthern MetropolitanSout...,598842,350.4,Stonnington City CouncilStonnington City Counc...
...,...,...,...,...,...,...,...,...,...,...,...,...
iOne,Yarraville,4/16 Dean St,3,t,620000.0,VB,16/04/2016,3013,Western Metropolitan,6543,6.3,Maribyrnong City Council
iProperty,Vermont,2/660 Canterbury Rd,3,t,820000.0,SP,3/06/2017,3133,Eastern Metropolitan,4181,17.2,Maroondah City Council
iSell,CranbourneNoble ParkSpringvaleNoble ParkSpring...,37 Boronia Av2 Parramatta Cr2 Gray St3 Christi...,402,hhhhhhhhhhhhhhhhhhhhhhhhuhhhhuhhhhhhhhhuhhhhhh...,71286000.0,PISSPISPIPISSSSSSNSSSSPISPISSPNSSWPIPIWSSSSSSS...,1/04/20171/04/20171/04/20171/07/20171/07/20171...,405137,South-Eastern MetropolitanSouth-Eastern Metrop...,969845,2815.4,Casey City CouncilGreater Dandenong City Counc...
iTRAK,The BasinBayswaterBoroniaSkyeCroydonBoroniaSt ...,65 Government Rd16 Wiltshire Av10 Weyburn Rd27...,248,hhhhhuuhuhhhuhhhhhuuhhthhhhhhuhhhhhhhhhhuhhhhu...,51405450.0,SPVBSPSPSSPISSWSPISSSSPSPISSPPISSSPSSSSSSSSPSS...,1/07/20173/06/20173/06/20173/09/20163/09/20173...,239758,Eastern MetropolitanEastern MetropolitanEaster...,508157,1848.4,Knox City CouncilKnox City CouncilKnox City Co...
voglwalpole,WarranwoodRingwood NorthRingwood EastRingwood ...,6 Warrangum Pl127 Warrandyte Rd1/29 Kemps St4/...,13,hhuu,1533000.0,SPSPVBS,2/06/201817/03/201824/02/201824/03/2018,12538,Eastern MetropolitanEastern MetropolitanEaster...,14028,82.4,Maroondah City CouncilManningham City CouncilM...